import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const satoshiLight = localFont({
  src: "../../public/fonts/Satoshi_Complete/Fonts/WEB/fonts/Satoshi-Light.woff",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${satoshiLight.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
